from typing import Optional

APP_COURSE_SOURCES: dict[str, str] = {
    "1": "Emovies",
    "2": "Ausjal",
}

APP_COUNTRIES = {
    "1": "Argentina",
    "2": "Bolivia",
    "3": "Brasil",
    "4": "Brazil",
    "5": "Canada",
    "6": "Chile",
    "7": "Colombia",
    "8": "Ecuador",
    "9": "El Salvador",
    "10": "Mexico",
    "11": "Nicaragua",
    "12": "Panamá",
    "13": "Paraguay",
    "14": "Peru",
    "15": "República Dominicana",
    "16": "Venezuela",
    "17": "España",
}

APP_COURSE_LEVELS = {
    "1": "Doctorado/Doctorate",
    "2": "Formación continua/ Continuous training",
    "3": "Posgrado/Postgraduate",
    "4": "Pregrado/Undergraduate",
    "5": "Técnico-Tecnológico Superior/ Technical-Technological",
}

APP_DISCIPLINARY_FIELDS = {
    "1": "Contabilidad",
    "2": "Ciencias administrativas",
    "3": "Agronomía y estudios de la tierra",
    "4": "Arquitectura y diseño",
    "5": "Artes",
    "6": "Ciencias Biológicas",
    "7": "Administración de empresas",
    "8": "Ingeniería Civil",
    "9": "Ciencias de la comunicación",
    "10": "Comunicación",
    "11": "Odontología",
    "12": "Ciencias económico-administrativas",
    "13": "Economía",
    "14": "Educación",
    "15": "Educación y pedagogía",
    "16": "Ingeniería Electrónica",
    "17": "Ingenierías",
    "18": "Finanzas",
    "19": "Artes gráficas y escénicas",
    "20": "Ciencias de la salud",
    "21": "Historia",
    "22": "Idiomas",
    "23": "Derecho",
    "24": "Literatura",
    "25": "Macroeconomía",
    "26": "Mercadotecnia y publicidad",
    "27": "Matemáticas",
    "28": "Microeconomía",
    "29": "Música",
    "30": "Nutrición",
    "31": "Salud y protección laboral",
    "32": "Otra Arte",
    "33": "Otra Ciencia de la comunicación",
    "34": "Otra Ciencia económico-administrativa",
    "35": "Otra Educación y pedagogía",
    "36": "Otra Ciencia de la salud",
    "37": "Otra Ciencia social o humanidad",
    "38": "Pedagogía",
    "39": "Filosofía y ética",
    "40": "Física",
    "41": "Artes plásticas",
    "42": "Ciencias politicas",
    "43": "Psicología",
    "44": "Servicios",
    "45": "Ciencias sociales y Humanidades",
    "46": "Sociología",
    "47": "Deportes",
    "48": "Veterinaria y zootecnia",
}

APP_UNIVERSITIES: dict[str, str] = {
    "1": "Benemérita Universidad Autónoma de Puebla",
    "2": "Centro Paula Souza",
    "3": "Corporación Tecnológica de Bogotá",
    "4": "Corporación Unificada Nacional de Educación Superior - CUN",
    "5": "Corporación Universidad de la Costa",
    "6": "Corporación Universitaria Iberoamericana - IBERO",
    "7": "Corporación Universitaria Minuto de Dios",
    "8": "Corporación Universitaria Remington",
    "9": "Corporación Universitaria Unitec",
    "10": "ESCUELA SUPERIOR POLITÉCNICA DE CHIMBORAZO",
    "11": "Escuela Superior Politécnica del Litoral",
    "12": "Faculdade Frassinetti do Recife - FAFIRE",
    "13": "Fundação Santo André",
    "14": "Fundación H.A. Barceló",
    "15": "Fundación Universidad de América",
    "16": "Fundación Universitaria Católica del Norte",
    "17": "Fundación Universitaria CEIPA",
    "18": "Fundación Universitaria de Ciencias de la Salud",
    "19": "Fundación Universitaria del Área Andina",
    "20": "Fundación Universitaria Juan N. Corpas",
    "21": "Fundación Universitaria Los Libertadores",
    "22": "Institución B",
    "23": "Institución Universitaria Esumer",
    "24": "Institución Universitaria ITM",
    "25": "Institución Universitaria Pascual Bravo",
    "26": "Instituto Politécnico Nacional",
    "27": "Instituto Superior de Formación Docente Salomé Ureña (ISFODOSU)",
    "28": "Instituto Tecnológico de las Américas",
    "29": "Instituto Universitario American College",
    "30": "Justice Institute of British Columbia",
    "31": "Lakehead University",
    "32": "Otra IES",
    "33": "Pontificia Universidad Católica Madre y Maestra",
    "34": "Pontifícia Universidade Católica do Rio Grande do Sul",
    "35": "Universidad Abierta para Adultos",
    "36": "Universidad Amazónica de Pando",
    "37": "Universidad Anáhuac Cancún",
    "38": "Universidad Anáhuac México",
    "39": "Universidad Anáhuac Xalapa",
    "40": "UNIVERSIDAD ANDINA DEL CUSCO",
    "41": "UNIVERSIDAD ANDRÉS BELLO",
    "42": "Universidad Antonio Nariño",
    "43": "Universidad Apec",
    "44": "UNIVERSIDAD ARTURO PRAT",
    "45": "Universidad Autónoma de Baja California",
    "46": "Universidad Autónoma de Chiapas",
    "47": "UNIVERSIDAD AUTÓNOMA DE CHIHUAHUA",
    "48": "Universidad Autónoma de Chile",
    "49": "Universidad Autónoma de Ciudad Juárez",
    "50": "Universidad Autónoma de Guerrero",
    "51": "Universidad Autónoma de La Laguna",
    "52": "Universidad Autónoma de Occidente",
    "53": "Universidad Autónoma de San Luis Potosí",
    "54": "Universidad Autónoma de Tlaxcala",
    "55": "Universidad Autónoma de Yucatán",
    "56": "Universidad Bolivariana del Ecuador",
    "57": "Universidad Católica Andrés Bello",
    "58": "Universidad Católica de Colombia",
    "59": "Universidad Católica de la Santísima Concepción",
    "60": "Universidad Católica de Santiago de Guayaquil",
    "61": "Universidad Católica de Temuco",
    "62": "Universidad Católica del Cibao",
    "63": "Universidad Católica Nordestana",
    "64": "Universidad Católica Tecnológica de Barahona",
    "65": "Universidad Central de Chile",
    "66": "UNIVERSIDAD CENTRAL DEL ESTE",
    "67": "UNIVERSIDAD CENTRAL DEL PARAGUAY",
    "68": "UNIVERSIDAD CÉSAR VALLEJO",
    "69": "Universidad Continental SAC",
    "70": "Universidad Cooperativa de Colombia",
    "71": "Universidad Cristóbal Colón",
    "72": "Universidad de Caldas",
    "73": "Universidad de Ciencias Aplicadas y Ambientales",
    "74": "Universidad de Ciencias y Humanidades",
    "75": "Universidad de Colima",
    "76": "Universidad de Concepción",
    "77": "Universidad de Córboda",
    "78": "Universidad de Cuenca",
    "79": "Universidad de Guadalajara",
    "80": "Universidad de Guanajuato",
    "81": "Universidad de Investigación de Tecnología Experimental Yachay",
    "82": "Universidad de La Frontera",
    "83": "UNIVERSIDAD DE LAS AMERICAS",
    "84": "Universidad de las Artes",
    "85": "UNIVERSIDAD DE LAS FUERZAS ARMADAS - ESPE",
    "86": "Universidad de Lima",
    "87": "Universidad de Los Lagos",
    "88": "Universidad de los Llanos",
    "89": "Universidad de Manizales",
    "90": "Universidad de Monterrey",
    "91": "Universidad de Morón",
    "92": "UNIVERSIDAD DE PLAYA ANCHA",
    "93": "Universidad de Quintana Roo",
    "94": "Universidad de San Buenaventura, Sede Bogotá",
    "95": "Universidad de Santiago de Chile",
    "96": "Universidad de Sonora",
    "97": "Universidad de Valparaíso",
    "98": "Universidad del Azuay",
    "99": "Universidad del Bío-Bío",
    "100": "Universidad del Claustro de Sor Juana",
    "101": "Universidad del Magdalena",
    "102": "Universidad del Pacífico",
    "103": "Universidad del Rosario",
    "104": "Universidad del Salvador",
    "105": "Universidad del Valle de Atemajac",
    "106": "Universidad Doctor Andrés Bello",
    "107": "Universidad EAN",
    "108": "Universidad Ecotec",
    "109": "Universidad El Bosque",
    "110": "Universidad Estatal de Bolívar",
    "111": "Universidad Estatal del Sur de Manabí",
    "112": "Universidad Evangélica de El Salvador",
    "113": "Universidad Franz Tamayo",
    "114": "UNIVERSIDAD GASTÓN DACHARY",
    "115": "Universidad Gerardo Barrios",
    "116": "Universidad Iberoamericana (UNIBE)",
    "117": "Universidad Iberoamericana Ciudad de México",
    "118": "UNIVERSIDAD IBEROAMERICANA DE CIENCIA Y TECNOLOGÍA (UNICIT)",
    "119": "Universidad Industrial de Santander",
    "120": "Universidad Internacional de Ciencia y Tecnología",
    "121": "Universidad La Gran Colombia",
    "122": "Universidad La Salle Bajio",
    "123": "Universidad Libre",
    "124": "Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca",
    "125": "Universidad Metropolitana - UNIMET",
    "126": "UNIVERSIDAD MILITAR NUEVA GRANADA",
    "127": "Universidad Nacional Abierta y a Distancia",
    "128": "Universidad Nacional Arturo Jauretche",
    "129": "Universidad Nacional de Córdoba",
    "130": "Universidad Nacional de Cuyo",
    "131": "Universidad Nacional de Hurlingham",
    "132": "UNIVERSIDAD NACIONAL DE LOJA",
    "133": "Universidad Nacional de Mar del Plata",
    "134": "Universidad Nacional de Río Negro",
    "135": "Universidad Nacional de San Juan",
    "136": "Universidad Nacional del Este",
    "137": "Universidad Nacional del Litoral",
    "138": "Universidad Nacional del Nordeste",
    "139": "Universidad Nacional del Noroeste de la Provincia de Buenos Aires",
    "140": "Universidad Nacional del Sur",
    "141": "Universidad Particular de Especialidades Espíritu Santo",
    "142": "Universidad Pedagógica de El Salvador \"Dr. Luis Alonso Aparicio\"",
    "143": "Universidad Piloto de Colombia",
    "144": "Universidad Politécnica Estatal del Carchi",
    "145": "Universidad Politécnica Salesiana",
    "146": "Universidad Privada Abierta Latinoamericana",
    "147": "Universidad Privada de Santa Cruz de la Sierra",
    "148": "Universidad Privada del Este",
    "149": "Universidad Privada del Norte",
    "150": "Universidad Privada del Valle",
    "151": "Universidad Privada Domingo Savio",
    "152": "Universidad Salvadoreña Alberto Masferrer",
    "153": "UNIVERSIDAD SAN GREGORIO DE PORTOVIEJO",
    "154": "Universidad Santo Tomás, Seccional Bogotá",
    "155": "Universidad Santo Tomás, Seccional Bucaramanga",
    "156": "Universidad Santo Tomás, Seccional Medellín",
    "157": "Universidad Santo Tomás, Seccional Tunja",
    "158": "Universidad Santo Tomás, Seccional Villavicencio",
    "159": "Universidad SEK",
    "160": "Universidad Técnica de Babahoyo",
    "161": "Universidad Técnica de Machala",
    "162": "Universidad Técnica Particular de Loja",
    "163": "Universidad Tecnológica de Bolívar",
    "164": "Universidad Tecnológica de Panamá",
    "165": "Universidad Tecnológica de Pereira",
    "166": "Universidad Tecnológica del Perú",
    "167": "Universidad Tecnológica Privada de Santa Cruz - UTEPSA",
    "168": "UNIVERSIDAD VASCO DE QUIROGA",
    "169": "Universidad Veracruzana",
    "170": "Universidade Alto Vale do Rio do Peixe - UNIARP",
    "171": "Universidade Comunitária da Região de Chapecó",
    "172": "Universidade da Região de Joinville - Univille",
    "173": "Universidade de Santa Cruz do Sul",
    "174": "Universidade do Estado de Santa Catarina",
    "175": "Universidade do Extremo Sul Catarinense",
    "176": "Universidade do Oeste de Santa Catarina",
    "177": "Universidade do Planalto Catarinense - UNIPLAC",
    "178": "UNIVERSIDADE DO VALE DO ITAJAÍ - UNIVALI",
    "179": "Universidade Federal de Pernambuco / UFPE",
    "180": "Universidade Federal de Rondonópolis - UFR",
    "181": "Universidade Federal de Uberlândia",
    "182": "Universidade Veiga de Almeida",
    "183": "Université du Québec à Trois-Rivières",
}

APP_LANGUAGES: dict[str, str] = {
    "1": "Español",
    "2": "Francés",
    "3": "Ingles",
    "5": "Portugués",
    "6": "Otro"
}

APP_CATALOG_MAP: dict[str, dict[str, str]] = {
    "countries": APP_COUNTRIES,
    "universities": APP_UNIVERSITIES,
    "languages": APP_LANGUAGES,
    "course_levels": APP_COURSE_LEVELS,
    "disciplinary_fields": APP_DISCIPLINARY_FIELDS,
    "course_sources": APP_COURSE_SOURCES,
}

def catalogValues(catalog: str) -> list[str]:
    return sorted(set(APP_CATALOG_MAP[catalog].values()))