APP_COUNTRIES = {
    "1": "Argentina",
    "2": "Bolivia",
    "3": "Brasil",
    "4": "Brazil",
    "5": "Canada",
    "6": "Chile",
    "7": "Colombia",
    "8": "Ecuador",
    "9": "El Salvador",
    "10": "Mexico",
    "11": "Nicaragua",
    "12": "Panamá",
    "13": "Paraguay",
    "14": "Peru",
    "15": "República Dominicana",
    "16": "Venezuela",
}

APP_COURSE_LEVELS = {
    "1": "Doctorado/Doctorate",
    "2": "Formación continua/ Continuous training",
    "3": "Posgrado/Postgraduate",
    "4": "Pregrado/Undergraduate",
    "5": "Técnico-Tecnológico Superior/ Technical-Technological",
}

APP_DISCIPLINARY_FIELDS = {
    "1": "Administración de empresas",
    "2": "Agronomía y estudios de la tierra",
    "3": "Arquitectura y diseño",
    "4": "Artes",
    "5": "Artes gráficas y escénicas",
    "6": "Artes plásticas",
    "7": "Biología",
    "8": "Ciencias administrativas",
    "9": "Ciencias Biológicas",
    "10": "Ciencias de la comunicación",
    "11": "Ciencias de la salud",
    "12": "Ciencias económico-administrativas",
    "13": "Ciencias exactas y naturales",
    "14": "Ciencias politicas",
    "15": "Ciencias sociales y Humanidades",
    "16": "Comunicación",
    "17": "Contabilidad",
    "18": "Deportes",
    "19": "Derecho",
    "20": "Economía",
    "21": "Educación",
    "22": "Educación y pedagogía",
    "23": "Enfermería",
    "24": "Farmacia",
    "25": "Filosofía y ética",
    "26": "Finanzas",
    "27": "Física",
    "28": "Geografía",
    "29": "Geología",
    "30": "Gestión empresarial",
    "31": "Historia",
    "32": "Hotelería y turismo",
    "33": "Idiomas",
    "34": "Ingeniería Civil",
    "35": "Ingeniería de Sistemas",
    "36": "Ingeniería Eléctrica",
    "37": "Ingeniería Electrónica",
    "38": "Ingeniería Industrial",
    "39": "Ingeniería Mecánica",
    "40": "Ingenierías",
    "41": "Literatura",
    "42": "Macroeconomía",
    "43": "Matemáticas",
    "44": "Medicina",
    "45": "Mercadotecnia y publicidad",
    "46": "Música",
    "47": "Negocios Internacionales",
    "48": "Nutrición",
    "49": "Odontología",
    "50": "Otra Arte",
    "51": "Otra Ciencia administrativa",
    "52": "Otra Ciencia Biológica",
    "53": "Otra Ciencia de la comunicación",
    "54": "Otra Ciencia de la salud",
    "55": "Otra Ciencia económico-administrativa",
    "56": "Otra Ciencia exacta o natural",
    "57": "Otra Ciencia social o humanidad",
    "58": "Otra Educación y pedagogía",
    "59": "Otra Ingeniería",
    "60": "Pedagogía",
    "61": "Periodismo",
    "62": "Psicología",
    "63": "Química",
    "64": "Religión y teología",
    "65": "Salud infantil",
    "66": "Salud y protección laboral",
    "67": "Servicios",
    "68": "Sociología",
    "69": "Terapia y rehabilitación",
    "70": "Trabajo Social",
    "71": "Veterinaria y zootecnia",
}

APP_UNIVERSITIES: dict[str, str] = {}

APP_LANGUAGES: dict[str, str] = {}

APP_CATALOG_MAP: dict[str, dict[str, str]] = {
    "countries": APP_COUNTRIES,
    "universities": APP_UNIVERSITIES,
    "languages": APP_LANGUAGES,
    "course_levels": APP_COURSE_LEVELS,
    "disciplinary_fields": APP_DISCIPLINARY_FIELDS,
}

def catalogValues(catalog: str) -> list[str]:
    return sorted(set(APP_CATALOG_MAP[catalog].values()))