EMOVIES_COUNTRIES = {
    "16": "Argentina",
    "17": "Bolivia",
    "43": "Brasil",
    "197": "Brazil",
    "6": "Canada",
    "18": "Chile",
    "19": "Colombia",
    "20": "Ecuador",
    "201": "El Salvador",
    "21": "Mexico",
    "199": "Nicaragua",
    "44": "Panamá",
    "194": "Paraguay",
    "22": "Peru",
    "45": "República Dominicana",
    "23": "Venezuela",
}

EMOVIES_COURSE_LEVELS = {
    "119": "Doctorado/Doctorate",
    "124": "Formación continua/ Continuous training",
    "79": "Posgrado/Postgraduate",
    "86": "Pregrado/Undergraduate",
    "112": "Técnico-Tecnológico Superior/ Technical-Technological",
}

EMOVIES_DISCIPLINARY_FIELDS = {
    "220": "Administración de empresas",
    "262": "Agronomía y estudios de la tierra",
    "322": "Arquitectura y diseño",
    "292": "Artes",
    "294": "Artes gráficas y escénicas",
    "296": "Artes plásticas",
    "326": "Biología",
    "218": "Ciencias administrativas",
    "260": "Ciencias Biológicas",
    "284": "Ciencias de la comunicación",
    "238": "Ciencias de la salud",
    "208": "Ciencias económico-administrativas",
    "324": "Ciencias exactas y naturales",
    "304": "Ciencias politicas",
    "302": "Ciencias sociales y Humanidades",
    "288": "Comunicación",
    "222": "Contabilidad",
    "342": "Deportes",
    "306": "Derecho",
    "210": "Economía",
    "344": "Educación",
    "340": "Educación y pedagogía",
    "240": "Enfermería",
    "242": "Farmacia",
    "308": "Filosofía y ética",
    "224": "Finanzas",
    "328": "Física",
    "330": "Geografía",
    "332": "Geología",
    "226": "Gestión empresarial",
    "310": "Historia",
    "228": "Hotelería y turismo",
    "346": "Idiomas",
    "270": "Ingeniería Civil",
    "280": "Ingeniería de Sistemas",
    "272": "Ingeniería Eléctrica",
    "274": "Ingeniería Electrónica",
    "276": "Ingeniería Industrial",
    "278": "Ingeniería Mecánica",
    "268": "Ingenierías",
    "312": "Literatura",
    "212": "Macroeconomía",
    "334": "Matemáticas",
    "244": "Medicina",
    "230": "Mercadotecnia y publicidad",
    "298": "Música",
    "232": "Negocios Internacionales",
    "246": "Nutrición",
    "248": "Odontología",
    "300": "Otra Arte",
    "236": "Otra Ciencia administrativa",
    "266": "Otra Ciencia Biológica",
    "290": "Otra Ciencia de la comunicación",
    "258": "Otra Ciencia de la salud",
    "216": "Otra Ciencia económico-administrativa",
    "338": "Otra Ciencia exacta o natural",
    "320": "Otra Ciencia social o humanidad",
    "350": "Otra Educación y pedagogía",
    "282": "Otra Ingeniería",
    "348": "Pedagogía",
    "286": "Periodismo",
    "250": "Psicología",
    "336": "Química",
    "314": "Religión y teología",
    "254": "Salud infantil",
    "252": "Salud y protección laboral",
    "234": "Servicios",
    "316": "Sociología",
    "256": "Terapia y rehabilitación",
    "318": "Trabajo Social",
    "264": "Veterinaria y zootecnia",
}

EMOVIES_UNIVERSITIES: dict[str, str] = {}

EMOVIES_LANGUAGES: dict[str, str] = {}

EMOVIES_CATALOG_MAP: dict[str, dict[str, str]] = {
    "countries": EMOVIES_COUNTRIES,
    "universities": EMOVIES_UNIVERSITIES,
    "languages": EMOVIES_LANGUAGES,
    "course_levels": EMOVIES_COURSE_LEVELS,
    "disciplinary_fields": EMOVIES_DISCIPLINARY_FIELDS,
}


def catalog_values(catalog: str) -> list[str]:
    return sorted(set(EMOVIES_CATALOG_MAP[catalog].values()))